#! /bin/bash

a="lists@blackwinter.de"
h="googlegroups.com"

function die() {
  echo "Usage: $0 {sub|unsub} <group>" >&2
  exit 1
}

function cmd() {
  mail -s "$2" -a "From: $a" "$1@$h" <<<""
}

[ $# -ne 2 ] && die

case "$1" in
  sub* )
    cmd "$2+subscribe"
    read -ep 'Request code: '
    cmd "$2+subconfirm" "[{$REPLY}]"
    ;;
  unsub* )
    cmd "googlegroups-manage+$2+unsubscribe"
    ;;
  * )
    die
    ;;
esac
