#! /bin/bash

function sum() {
  mem="$(echo $(ps -C ${1// /,} -o $2 --no-headers))"
  echo $((($(echo "${mem// /+}")+0)/1024))
}

arg="$(echo $*)"

vsz="$(sum "$arg" vsz)"
rss="$(sum "$arg" rss)"

echo "$vsz $rss"
