#! /bin/bash

s="sleep 0.1"

t="$(mktemp)"
while [ -n "$1" ]; do
  echo "title: %w [$1];; command: $1;; workdir: ~" >> "$t"; shift
done

${MULTI_KONSOLE:-konsole} --tabs-from-file "$t" -e $s 2>/dev/null &

q="qdbus org.kde.konsole-$!"; i=0
until $q &>/dev/null || [ $i -gt 100 ]; do $s; ((i++)); done

rm "$t"
