#! /bin/bash

set -e

c="/etc/apache2/conf-available/local-passenger.conf"
l="ruby"

sudo gem update passenger

passenger-install-apache2-module --snippet | sudo tee "$c"
sudo passenger-install-apache2-module --auto --languages "$l"

sudo systemctl restart apache2
