#! /bin/bash

PASSENGER_CONF="/etc/apache2/conf.d/passenger"
[ ! -r "$PASSENGER_CONF" ] && echo "File not found: $PASSENGER_CONF" && exit 1

[ "`id -u`" -ne 0 ] && sudo="sudo"

function step() {
  read -ep "$1? (y/n) [y]: "
  [ "$REPLY" = "n" ] && exit
}

step "Update Passenger"
$sudo gem update passenger

version="$(gem specification passenger version | awk '/^ *version:/{print $2}')"
dirname="$(readlink -f "$(awk '/^PassengerRoot/{print $2}' "$PASSENGER_CONF")")"

if [ "$(basename "$dirname")" != "passenger-$version" ]; then
  echo "PassengerRoot not up-to-date: $dirname (expected $version)" && exit 1
fi

step "Install Apache 2 module"
$sudo passenger-install-apache2-module

step "Restart Apache"
$sudo invoke-rc.d apache2 restart
