#! /usr/bin/ruby

require 'rubygems'

gem 'blackwinter-gnuplot'
require 'gnuplot'

Gnuplot.plot { |plot|
  plot.xrange ARGV.shift if ARGV.first =~ /\A\[(?:-?\d+)?:(?:-?\d+)?\]\z/

  ARGV.each { |function| plot.data(function) { |ds|
    ds.with = 'lines'
    ds.linewidth = 1
  } }
}
