#! /usr/bin/ruby

require 'rubygems'
require 'gnuplot'

Gnuplot.open { |gp|
  Gnuplot::Plot.new(gp) { |plot|
    plot.xrange ARGV.shift if ARGV.first =~ /\A[\[(]-?\d*:-?\d*[)\]]\z/

    ARGV.each { |function|
      plot.data << Gnuplot::DataSet.new(function) { |ds|
        ds.with = 'lines'
        ds.linewidth = 1
      }
    }
  }
}
