#! /usr/bin/env ruby

load File.join(__dir__, 'plotcsv')

Plot.plot { |plot|
  plot.xrange ARGV.shift if ARGV.first =~ /\A\[(?:-?\d+)?:(?:-?\d+)?\]\z/

  ARGV.each { |function| plot.data(function) { |ds|
    ds.with = 'lines'
    ds.linewidth = 1
  } }
}
