#! /bin/bash

interval=1
count=
pgrep=

usage="Usage: $0 [-N <count>] [-I <interval=$interval>] {<ps-args>...|-R <pgrep-args>...}"

while getopts :I:N:Rh opt; do
  case "$opt" in
    I ) interval="$OPTARG";;
    N ) count="$OPTARG";;
    R ) pgrep=1;;
    h ) echo "$usage"; exit;;
    * ) ((OPTIND--)); break;;
  esac
done

shift $((OPTIND - 1))
[ $# -eq 0 ] && echo "$usage" && exit 1

ps=$@
[ -n "$pgrep" ] && until ps=$(pgrep "$@"); do :; done

while ps -o vsz,rss,sz,%mem,%cpu,time,etime,pid $headers $ps; do
  [ -n "$count" ] && [ $((++j)) -ge $count ] && exit
  sleep $interval || exit 1
  headers=--no-headers
done
