#! /bin/bash

set -o pipefail

count=
file=/dev/stdout
interval=1
pid=

usage="Usage: $0 [-c <count>] [-i <interval=$interval>] [-o <file>] {-p <pid>|<cmd> [<arg>...]}"

while getopts i:c:ho:p: opt; do
  case "$opt" in
    c ) count="$OPTARG";;
    h ) echo "$usage"; exit;;
    i ) interval="$OPTARG";;
    o ) file="$OPTARG";;
    p ) pid="$OPTARG";;
  esac
done

shift $((OPTIND - 1))

if [ -z "$pid" ]; then
  [ $# -eq 0 ] && echo "$usage" && exit 1

  "$@" &
  pid=$!

  trap "kill $pid" INT TERM
  echo "$0: [$pid] $@"
fi

while ps -o vsz,rss,sz,%mem,%cpu,time,etime,pid $headers $pid | sed 's/^ *//; s/ \+/,/g'; do
  [ -n "$count" ] && [ $((++j)) -ge $count ] && break
  sleep $interval || break
  headers=--no-headers
done >"$file"

wait
