#! /bin/bash

function info() {
  svn info "$1" | awk "/^$2:/{print \$$3}"
}

trac="$(info . 'Repository Root' 3 | sed 's:/svn/:/trac/:')"

while [ -n "$1" ]; do
  path="$1"; shift

  if [[ "$path" =~ ^r[0-9]+$ ]]; then
    part="changeset"
    path="${path/r}"
  elif [[ "$path" =~ ^#[0-9]+$ ]]; then
    part="ticket"
    path="${path/\#}"
  else
    part="browser"
    path="$(info "$path" 'URL' 2 | sed 's:.*/svn/[^/]\+/::')"
  fi

  x-www-browser "$trac/$part/$path"
done
